server:
  port: 8091


eureka:
  instance:
    hostname: localhost

  client:
    service-url:
     defaultZone: http://localhost:8881/eureka/,http://localhost:8882/eureka/,http://localhost:8883/eureka/
spring:
  application:
    name: UserFeignConsumer