server:
  port: 8881

eureka:
  instance:
    hostname: eureka01
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 6
  client:
    service-url:
      defaultZone: http://eureka02:8882/eureka/,http://eureka03:8883/eureka/

    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: EurekaCenter